stages:
  - pytest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

run_pytest:
  stage: pytest
  image: cpalmer718/snakemake-gcc
  script:
    - mamba install pytest-cov
    - pip install hypothesis
    - pytest --cov | awk '/^TOTAL/ {print $4}' | sed 's/%//' | awk '{print \"Final coverage:\t\"$0}'
  coverage: '/Final coverage: \d+\.?\d*/'
