name: qtl_power
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - tqdm
    - pytest-cov
    - pytest-xdist
    - hypothesis
